name: hack_03
channels:
  # - intel
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - pyarrow
  - tqdm
  - xgboost
  - networkx
  - joblib
  - nomkl
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - sentence-transformers
      - transformers