name: hack_03
channels:
  # - intel
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - pyarrow
  - tqdm
  - xgboost
  - lightgbm
  - networkx
  - joblib
  - nomkl
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - shap
  - lime
  - pip:
      - sentence-transformers
      - transformers